server:
  port: 8080
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: mycert

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
jwt:
  secret: 9df8505bb4eb7833d0f07cebec765d065344850a4548a5f8c3a9ffea5c01e6bd
logging:
  level:
    root: error
    org.javacode.employee_accounting.security.filter: info
    org.javacode.employee_accounting.service.impl: warn
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  file:
    name: logs/employee_accounting.log